server:
  servlet:
    context-path: /despesa-pessoa/api

springdoc:
  swagger-ui:
    path: /public/swagger

spring:
  data:
    mongodb:
      uri: mongodb://{despesaclienteapi}:{despesaclienteapi}@localhost:27017
      database: boot-mongodb